language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
env:
  global:
    - CC_TEST_REPORTER_ID=fc2dab3f5cb43356a01351fc2303e4e1274c372dee85d7a1b68fe6204b2e1c3b

# command to install dependencies
install:
  - pip install coverage
# command to run tests
before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --omit=test.py test.py
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT



